#!/usr/bin/env bash
set -euo pipefail
set +u
source /usr/local/opt/chruby/share/chruby/chruby.sh
chruby ruby
set -u

bundle install --quiet

echo "--- xcodebuild"
bundle exec xcodebuild -project 'ProcedureKit.xcodeproj' -scheme 'iOS' -destination 'platform=iOS Simulator,name=iPhone X' -derivedDataPath .ci/xcodebuild-data/ -enableCodeCoverage YES clean test | tee .ci/results/xcodebuild.log | xcpretty
